class MainRunner1{
 public static void main(String[] args)
 {
  System.out.println("start main in mainrunner");
  Fish fish=new Fish("Angelfish",2);
  System.out.println("fish");
  Fish fish1=new Fish("Gourami",3);
  System.out.println("fish1");
  Fish fish2=new Fish("Swordfish",5);
  System.out.println("fish2");
  Fish fis3=new Fish("Koi",4);
  System.out.println("fish3");
  Fish fish4=new Fish("Guppy",2);
  System.out.println("fish4");
  Fish fish5=new Fish("Clownfish",3);
  System.out.println("fish5");
  Fish fish6=new Fish("Tetra",1);
  System.out.println("fish6");
  Fish fish7=new Fish("Snapper",6);
  System.out.println("fish7");
  Fish fish8=new Fish("Flounder",4);
  System.out.println("fish8");
  Fish fish9=new Fish("Pufferfish",3);
  System.out.println("fish9");
  Fish fish10=new Fish("Bhootai",3);
  System.out.println("fish10");
  
  Lamp lamp=new Lamp("Silver",65);
  System.out.println("lamp"); 
  Lamp lamp1=new Lamp("Bronze",55);
  System.out.println("lamp1"); 
  Lamp lamp2=new Lamp("Chrome",75);
  System.out.println("lamp2"); 
  Lamp lamp3=new Lamp("Copper",80);
  System.out.println("lamp3"); 
  Lamp lamp4=new Lamp("Nickel",90);
  System.out.println("lamp4"); 
  Lamp lamp5=new Lamp("Brass",85);
  System.out.println("lamp5"); 
  Lamp lamp6=new Lamp("Aluminum",45);
  System.out.println("lamp6"); 
  Lamp lamp7=new Lamp("Steel",35);
  System.out.println("lamp7"); 
  Lamp lamp8=new Lamp("Plastic",95);
  System.out.println("lamp8"); 
  Lamp lamp9=new Lamp("Glass'",100);
  System.out.println("lamp9"); 
  Lamp lamp10=new Lamp("Wood",105);
  System.out.println("lamp10");

   PrintingMachine printingmachine=new PrintingMachine("Epson",40);
   System.out.println("printingmachine");
   PrintingMachine printingmachine1=new PrintingMachine("Canon", 45);
   System.out.println("printingmachine1");
   PrintingMachine printingmachine2=new PrintingMachine("Brother",40);
   System.out.println("printingmachine2");
   PrintingMachine printingmachine3=new PrintingMachine("Samsung",50);
   System.out.println("printingmachine3");
   PrintingMachine printingmachine4=new PrintingMachine("Lexmark",60);
   System.out.println("printingmachine4");
   PrintingMachine printingmachine5=new PrintingMachine("Sharp",60);
   System.out.println("printingmachine5");
   PrintingMachine printingmachine6=new PrintingMachine("Panasonic",70);
   System.out.println("printingmachine6");
   PrintingMachine printingmachine7=new PrintingMachine("Kyocera",75);
   System.out.println("printingmachine7");
   PrintingMachine printingmachine8=new PrintingMachine("Xerox",80);
   System.out.println("printingmachine8");
   PrintingMachine printingmachine9=new PrintingMachine("Ricoh",85);
   System.out.println("printingmachine9");
   PrintingMachine printingmachine10=new PrintingMachine("HP",90);
   System.out.println("printingmachine10");
   
  Lens lens =new Lens("Macro", 85);
  System.out.println(lens);
  Lens lens1 =new Lens("Telephoto", 100);
  System.out.println(lens1);
  Lens lens2 =new Lens("Wide-angle", 24);
  System.out.println(lens2);
  Lens lens3 =new Lens("Zoom", 200);
  System.out.println(lens3);
  Lens lens4 =new Lens("Prime", 50);
  System.out.println(lens4);
  Lens lens5 =new Lens("Standard", 35);
  System.out.println(lens5);
  Lens lens6 =new Lens("Portrait", 85);
  System.out.println(lens6);
  Lens lens7 =new Lens("Cine", 75);
  System.out.println(lens7);
  Lens lens8 =new Lens("Fisheye", 15);
  System.out.println(lens8);
  Lens lens9 =new Lens("Tilt-shift", 45);
  System.out.println(lens9);
  Lens lens10=new Lens("Infrared", 60);
  System.out.println(lens10);
  
  Coil coil1 =new Coil("Copper", 10.5);
  System.out.println(coil1);
  Coil coil2 =new Coil("Aluminum", 20.3);
  System.out.println(coil2);
  Coil coil3 =new Coil("Steel", 15.8);
  System.out.println(coil3);
  Coil coil4 =new Coil("Brass", 18.9);
  System.out.println(coil4);
  Coil coil5 =new Coil("Nickel", 14.7);
  System.out.println(coil5);
  Coil coil6 =new Coil("Silver", 16.5);
  System.out.println(coil6);
  Coil coil7 =new Coil("Titanium", 19.3);
  System.out.println(coil7);
  Coil coil8 =new Coil("Gold", 13.8);
  System.out.println(coil8);
  Coil coil9 =new Coil("Platinum", 17.2);
  System.out.println(coil9);
  Coil coil10 =new Coil("Zinc", 12.6);
  System.out.println(coil10);
  Coil coil11 =new Coil("Lead", 11.4);
  System.out.println(coil11);
  
  
  Cap cap1 =new Cap("Nike", "Red", 7.0);
  System.out.println(cap1);
  Cap cap2 =new Cap("Adidas", "Blue", 6.5);
  System.out.println(cap2);
  Cap cap3 =new Cap("Puma", "Black", 7.5);
  System.out.println(cap3);
  Cap cap4 =new Cap("Reebok", "White", 6.0);
  System.out.println(cap4);
  Cap cap5 =new Cap("Under Armour", "Green", 7.0);
  System.out.println(cap5);
  Cap cap6 =new Cap("New Balance", "Yellow", 6.8);
  System.out.println(cap6);
  Cap cap7 =new Cap("Asics", "Pink", 7.2);
  System.out.println(cap7);
  Cap cap8 =new Cap("Fila", "Purple", 6.3);
  System.out.println(cap8);
  Cap cap9 =new Cap("Champion", "Orange", 7.1);
  System.out.println(cap9);
  Cap cap10 =new Cap("Converse", "Brown", 6.7);
  System.out.println(cap10);
  Cap cap11 =new Cap("Vans", "Grey", 7.4);
  System.out.println(cap11);
  
  Gold gold1 =new Gold(99.9, 20.0, "South Africa");
  System.out.println(gold1);
  Gold gold2 =new Gold(99.5, 15.0, "Australia");
  System.out.println(gold2);
  Gold gold3 =new Gold(99.7, 25.0, "Russia");
  System.out.println(gold3);
  Gold gold4 =new Gold(99.8, 30.0, "USA");
  System.out.println(gold4);
  Gold gold5 =new Gold(99.6, 18.0, "China");
  System.out.println(gold5);
  Gold gold6 =new Gold(99.9, 22.0, "Canada");
  System.out.println(gold6);
  Gold gold7 =new Gold(99.4, 10.0, "Brazil");
  System.out.println(gold7);
  Gold gold8 =new Gold(99.7, 28.0, "India");
  System.out.println(gold8);
  Gold gold9 =new Gold(99.3, 12.0, "Peru");
  System.out.println(gold9);
  Gold gold10 =new Gold(99.8, 35.0, "Mexico");
  System.out.println(gold10);
  Gold gold11 =new Gold(99.6, 15.0, "Ghana");
  System.out.println(gold11);
  
  Board board1 =new Board("Plywood", 4.0, 8.0);
  System.out.println(board1);
  Board board2 =new Board("Chipboard", 4.0, 8.0);
  System.out.println(board2);
  Board board3 =new Board("MDF", 4.0, 8.0);
  System.out.println(board3);
  Board board4 =new Board("OSB", 4.0, 8.0);
  System.out.println(board4);
  Board board5 =new Board("HDF", 4.0, 8.0);
  System.out.println(board5);
  Board board6 =new Board("Particle Board", 4.0, 8.0);
  System.out.println(board6);
  Board board7 =new Board("Fiberboard", 4.0, 8.0);
  System.out.println(board7);
  Board board8 =new Board("Veneer", 4.0, 8.0);
  System.out.println(board8);
  Board board9 =new Board("Laminated Board", 4.0, 8.0);
  System.out.println(board9);
  Board board10 =new Board("Marine Plywood", 4.0, 8.0);
  System.out.println(board10);
  Board board11 =new Board("Hardboard", 4.0, 8.0);
  System.out.println(board11);

  Led led1 =new Led(800, "White", 12.0);
  System.out.println(led1);
  Led led2 =new Led(600, "Yellow", 9.0);
  System.out.println(led2);
  Led led3 =new Led(1000, "Blue", 15.0);
  System.out.println(led3);
  Led led4 =new Led(500, "Red", 8.0);
  System.out.println(led4);
  Led led5 =new Led(700, "Green", 10.0);
  System.out.println(led5);
  Led led6 =new Led(900, "Purple", 13.0);
  System.out.println(led6);
  Led led7 =new Led(1100, "Orange", 16.0);
  System.out.println(led7);
  Led led8 =new Led(750, "Pink", 11.0);
  System.out.println(led8);
  Led led9 =new Led(650, "Cyan", 9.5);
  System.out.println(led9);
  Led led10 =new Led(1200, "Magenta", 17.0);
  System.out.println(led10);
  Led led11 =new Led(850, "Warm White", 12.5);
  System.out.println(led11);
  
  SimCard sim1 =new SimCard("AT&T", "123-456-7890", "Unlimited");
  System.out.println(sim1);
  SimCard sim2 =new SimCard("Verizon", "234-567-8901", "Prepaid");
  System.out.println(sim2);
  SimCard sim3 =new SimCard("T-Mobile", "345-678-901", "Family");
  System.out.println(sim3);
  SimCard sim4 =new SimCard("Sprint", "456-789-0123", "Business");
  System.out.println(sim4);
  SimCard sim5 =new SimCard("Vodafone", "567-890-1234", "Data Only");
  System.out.println(sim5);
  SimCard sim6 =new SimCard("Orange", "678-901-2345", "Pay-as-you-go");
  System.out.println(sim6);
  SimCard sim7 =new SimCard("Airtel", "789-012-3456", "International");
  System.out.println(sim7);
  SimCard sim8 =new SimCard("Jio", "890-123-4567", "Postpaid");
  System.out.println(sim8);
  SimCard sim9 =new SimCard("MTN", "901-234-5678", "Unlimited");
  System.out.println(sim9);
  SimCard sim10 =new SimCard("Glo", "012-345-6789", "Family");
  System.out.println(sim10);
  SimCard sim11 =new SimCard("BSNL", "123-456-7891", "Business");
  System.out.println(sim11);

 }
}