class Infomation{
 public static void main(String[] args){
   String name="hashini";
   System.out.println(name);
   String place="from mysore";
   System.out.println(place);
   String age="age is 24";
   System.out.println(age);
   String email="hashini@gmail.com";
   System.out.println(email);
   String password="hashini@123";
   System.out.println(password);
   String moblieno="9855412421";
   System.out.println(moblieno);
   String education="B.com";
   System.out.println(education);
   String college="Malnad college hassan.";
   System.out.println(college);
   String accountno="123466787900907";
   System.out.println(accountno);
   String bankname="state bank";
   System.out.println(bankname);
   String branch="mysore";
   System.out.println(branch);
   String bottle="500 ml of water is 10 rupees";
   System.out.println(bottle);
   String order="I order a food and ";
   System.out.println(order);
   String distance="from mysore to hassan ";
   System.out.println(distance);
   String distan="around 120 km";
   System.out.println(distan);
   String petrol="petrol rate very high";
   System.out.println(petrol);
   String diesel="and diesel rate";
   System.out.println(diesel);
   String rate="also high";
   System.out.println(rate);
   String govt="government charge the tax";
   System.out.println(govt);
   String box="box have somethings";
   System.out.println(box);
   String msg="The quick brown";
   System.out.println(msg);
   String animal="fox jumps over the lazy dog";
   System.out.println(animal);
   String nam="Lorem ipsum dolor ";
   System.out.println(nam); 
   String monye="sit amet, ";
   System.out.println(monye); 
   String text="consectetur ";
   System.out.println(text);
   String content="adipiscing elit. ";
   System.out.println(content); 
   String tech="Technology shapes ";
   System.out.println(tech);
   String futer="the future and improves";
   System.out.println(futer); 
   String live="our lives daily.";
   System.out.println(live); 
   String trand="Artificial Intelligence is ";
   System.out.println(trand); 
   String global="revolutionizing industries globally.";
   System.out.println(global); 
   String masg="Sustainability is crucial";
   System.out.println(masg); 
   String health="for the planet's health";
   System.out.println(health); 
   String empowers="Education empowers individuals and transforms communities. ";
   System.out.println(empowers); 
   String pgm="Innovation drives progress and fosters creativity. ";
   System.out.println(pgm); 
   String save="Healthcare advancements save lives and enhance well-being. " ;
   System.out.println(save); 
   String people="Connectivity brings people closer and enables collaboration. " ;
   System.out.println(people); 
   String exam="Exploration expands our understanding of the universe.";
   System.out.println(exam); 
   String jug="Pack my box with five dozen liquor jugs. ";
   System.out.println(jug); 
   String big="Jinxed wizards pluck ivy from the big quilt. ";
   System.out.println(big); 
   String jump="The five boxing wizards jump quickly. ";
   System.out.println(jump); 
   String daft="How vexingly quick daft zebras jump! " ;
   System.out.println(daft); 
   String dozy="Bright vixens jump; dozy fowl quack. ";
   System.out.println(dozy); 
   String jim="Quick zephyrs blow, vexing daft Jim. ";
   System.out.println(jim); 
   String judge="Sphinx of black quartz, judge my vow. ";
   System.out.println(judge); 
   String alphabets="A B C ..... Z";
   System.out.println(alphabets); 
   String nopeple="1000";
   System.out.println(nopeple); 
   String address="Mangalore";
   System.out.println(address); 
   String book="vidhya";
   System.out.println(book); 
   String buss="Rajahamsha";
   System.out.println(buss); 
   String auto="KA-05";
   System.out.println(auto); 
   String str="A";
   System.out.println(str); 
   String home="#1355";
   System.out.println(home); 
   String atm="canarabankatm";
   System.out.println(atm); 
   String cond="true";
   System.out.println(cond); 
   String date="28/09/23";
   System.out.println(date); 
   String days="365days in a year";
   System.out.println(days); 
   String names="sindhu,nithya";
   System.out.println(names); 
   String clgbranch="computer science";
   System.out.println(clgbranch); 
   String sec=name+place;
   System.out.println(sec); 
   String combine=sec+age;
   System.out.println(combine); 
   String signin=email+password;
   System.out.println(signin); 
   String done=signin+"login";
   System.out.println(done);
   String mis=education+college;
   System.out.println(mis); 
   String abb=accountno+bankname+branch;
   System.out.println(abb); 
   String ani=msg+animal;
   System.out.println(ani); 
   String food=order+bottle;
   System.out.println(food); 
   String dis=distance+distan;
   System.out.println(dis); 
   String fule=petrol+diesel;
   System.out.println(fule); 
   String con=nam+monye;
   System.out.println(con); 
   String j=jim+jump;
   System.out.println(j); 
   String s=text+content;
   System.out.println(s); 
   String techonology=tech+futer+live;
   System.out.println(techonology); 
   String transforms=trand+global;
   System.out.println(transforms); 
   String tex=masg+health;
   System.out.println(tex); 
   String decition=tex+"?";
   System.out.println(decition); 
   String trio=empowers+pgm;
   System.out.println(trio); 
   String down=save+people;
   System.out.println(down); 
   String one=down+save;
   System.out.println(one); 
   String state="karnataka"+"tamilnadu";
   System.out.println(state); 
   String file=jug+big;
   System.out.println(file); 
   String comb=jim+judge;
   System.out.println(comb); 
   String numb=food+nopeple;
   System.out.println(numb); 
   String inform=name+place+age+email+password;
   System.out.println(inform); 
}
}